package MainClass;

import MyClass.MyImgJpanel;

import javax.swing.*;
import java.awt.*;

/**
 * 第一个窗口类
 *
 * @author 嘿 林梓鸿
 * @date 2019年 11月25日 17:58:20
 */
public class MainStartJframe extends JFrame {
    /**
     * buttonGroup -> 按钮组
     */
    private javax.swing.ButtonGroup buttonGroup;



    /**
     * BgJPanel -> 背景图片
     */
    private javax.swing.JPanel BgJPanel;

    /**
     * StartJPanel -> 开始图片
     */
    private javax.swing.JPanel StartJPanel;

    /**
     * EasyButton -> 简单按钮
     */
    private javax.swing.JRadioButton EasyButton;

    /**
     * CommonButton -> 普通按钮
     */
    private javax.swing.JRadioButton CommonButton;

    /**
     * DifficultyButton -> 困难按钮
     */
    private javax.swing.JRadioButton DifficultyButton;

    /**
     * monsterInterval -> 怪物出现的时间间隔,由窗口1传递过来。默认为一般
     * 简单为 -1 即每波怪物的时间间隔比默认值多1s
     * 一般为 0 即每波怪物的时间间隔一致
     * 困难为 1 即每波怪物的时间间隔比默认值少1
     */
    private int monsterInterval = 0;

    /**
     * monsterSpeed -> 怪物走动的速度,即线程刷新的快慢
     */
    private int monsterSpeed = 20;


    private int monsterStep = 3;            //怪物默认步数，默认为简单难度
    private int monsterAttack = 10;         //怪物默认攻击力值，默认为简单难度攻击力值
    private int monsterHP = 100;            //怪物默认血量，默认为简单难度血量值



    /**
     * Creates new form NewJFrame
     * 构造方法直接生成窗口
     */
    public MainStartJframe() {
        super("Tower Defense Game");

        initComponents();//初始化的方法

        this.setLocationRelativeTo(null);
        //居中显示


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 从构造函数中调用此方法来初始化窗体
     *警告:不要修改此代码。这个方法的内容总是由表单编辑器重新生成
     */
    @SuppressWarnings("unchecked")//告诉编译器忽略 unchecked 警告信息
    // <editor-fold defaultstate="collapsed" desc="Generated Code">


    private void initComponents() {
        this.setSize(getWidth(),getHeight());
        //设置窗口的大小

        this.setResizable(false);
        //设置窗口大小不可更改

        buttonGroup = new javax.swing.ButtonGroup();

        /*
         *新建背景面板
         * 首先，paintComponent()是swing的一个方法，相当于图形版的main()，是会自执行的。
         * 因此要重写此方法
         * 让它变成把图片画成背景
         */
        BgJPanel = new MyImgJpanel("Image/bg.jpg");


        StartJPanel = new MyImgJpanel("Image/start.png");


        StartJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartJPanelMouseClicked(evt);
            }
        });


        StartJPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        //开始图片那里鼠标变成手


        EasyButton = new javax.swing.JRadioButton();
        CommonButton = new javax.swing.JRadioButton();
        DifficultyButton = new javax.swing.JRadioButton();

        buttonGroup.add(EasyButton);
        buttonGroup.add(CommonButton);
        buttonGroup.add(DifficultyButton);

        /*
        按钮添加到按钮组里可保证只能选择一个
         */



        setDefaultCloseOperation(EXIT_ON_CLOSE);
        //设置用户在此窗体上发起 "close" 时默认执行System.exit(0)



        /*
         *以下代码是netbean自动生成的
         * 有点复杂
         */

        GroupLayout startLayout = new GroupLayout(StartJPanel);
        //GroupLayout 分组布局
        StartJPanel.setLayout(startLayout);
        //设置布局


        startLayout.setHorizontalGroup(
                //设置水平组
                startLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 187, Short.MAX_VALUE)
        );


        startLayout.setVerticalGroup(
                //设置垂直组
                startLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 82, Short.MAX_VALUE)
        );


        EasyButton.setText("简单");
        EasyButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        //添加监听事件

        CommonButton.setText("普通");
        CommonButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commonButtonActionPerformed(evt);
            }
        });

        DifficultyButton.setText("困难");
        DifficultyButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                difficultyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BgLayout = new javax.swing.
                GroupLayout(BgJPanel);
        BgJPanel.setLayout(BgLayout);
        //背景分组布局


        BgLayout.setHorizontalGroup(
                BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BgLayout.createSequentialGroup()
                                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BgLayout.createSequentialGroup()
                                                .addGap(332, 332, 332)
                                                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(CommonButton)
                                                        .addComponent(DifficultyButton)
                                                        .addComponent(EasyButton)))
                                        .addGroup(BgLayout.createSequentialGroup()
                                                .addGap(267, 267, 267)
                                                .addComponent(StartJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(297, Short.MAX_VALUE))
        );
        //水平


        BgLayout.setVerticalGroup(
                BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BgLayout.createSequentialGroup()
                                .addContainerGap(217, Short.MAX_VALUE)
                                .addComponent(StartJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EasyButton)
                                .addGap(2, 2, 2)
                                .addComponent(CommonButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DifficultyButton)
                                .addGap(86, 86, 86))
        );
        //垂直

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        //ContentPane分组布局



        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BgJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        /*
         java 程序种经常用到Frame.pack()；
　　      Frame.pack()这个方法的作用就是根据窗口里面的布局及组件的preferedSize来确定frame的最佳大小。
         */




    }// </editor-fold>

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.monsterInterval = -1;
        this.monsterStep = 3;
        this.monsterAttack = 10;
        this.monsterHP = 100;
    }

    private void commonButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.monsterInterval = 0;
        this.monsterStep = 5;
        this.monsterAttack = 15;
        this.monsterHP = 100;
    }
    private void difficultyButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.monsterInterval = 1;
        this.monsterStep = 5;
        this.monsterAttack = 20;
        this.monsterHP = 120;
    }
    private void StartJPanelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

        this.dispose();
        //关闭此窗口


        new MainGameJframe(monsterInterval,monsterStep,monsterAttack,monsterHP).setVisible(true);
        //生成游戏界面窗口

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*
        /*设置光轮外观和感觉*/
        //<编辑-折叠defaultstate=" " desc="外观设置代码(可选)" >
        /*如果Nimbus(在Java SE 6中引入)不可用，保持默认的外观和感觉。
         *详情请见http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         * /
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStartJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStartJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStartJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStartJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainStartJframe().setVisible(true);
            }
        });
    }
}
